### ISSUE TITLE
Getting only the upper triangle from a distance object

### ISSUE THREAD

**Issue by LimaRAF** [fsavje/distances#5]
Dear @fsavje,

This is not exactly an issue but more an advice on how to manipulate the output of distances::distances.

I am trying to get mean distances per group. I was using at first the stats::dist but it was much slower. However, I was not able to obtain only the upper/lower triangle of the distances object to make the mean calculations. Any thoughts on how to do it using function distances and getting the same result as dist (without having to index the output matrix using upper.tri/lower tri function)?

Here you are an example with a small dataset:
```
set.seed(1)
mydf <- data.frame(X = c(-46,-52,-54,-52,-47,-50),
                   Y = c(-22,-26,-23,-25,-23,-22),
                   tax = sample(c("a", "b"), 6, replace = TRUE),
                   stringsAsFactors = FALSE)

#using dist
all.dist <- dist(mydf[, 1:2])
mean(as.matrix(all.dist), na.rm = TRUE) # 3.80
mean(dist(mydf[mydf$tax == "a", 1:2]), na.rm = TRUE) # 4.81
mean(dist(mydf[mydf$tax == "b", 1:2]), na.rm = TRUE) # 3.51
tapply(1:nrow(mydf), mydf$tax, 
                                function(x) mean(dist(mydf[x, 1:2]), na.rm = TRUE)) #4.81 and 3.51

#using distances
all.dist2 <- distances::distances(mydf[,1:2])
mean(as.matrix(all.dist2), na.rm = TRUE) # 3.8
mean(as.matrix(distances(mydf[mydf$tax == "a", 1:2])), na.rm = TRUE) # 3.21
mean(as.matrix(distances(mydf[mydf$tax == "b", 1:2])), na.rm = TRUE) # 2.34
tapply(1:nrow(mydf), mydf$tax, 
                       function(x) mean(as.matrix(distances::distances(mydf[x, 1:2])), na.rm = TRUE))
tapply(1:nrow(mydf), mydf$tax, 
       function(x) mean(as.matrix(distances::distances(mydf[x, 1:2]))[upper.tri(as.matrix(distances::distances(mydf[x, 1:2])))], na.rm = TRUE))

```

Thank you in advance.

**Comment by fsavje** [comment]
Hi @LimaRAF,

As you probably already know, the difference between the two approaches in your code is that the first omits the diagonal from the mean, while the second includes it. This is because the object returned by `dist()` is a vector that only stores the upper triangle, and the `mean()` function falls back to the underlying object. The command `as.matrix()` returns the full distance matrix, so it includes also the diagonal.

There are several ways to get what you want:

1. Since we know the diagonal is zero, the difference is only in the denominator. In particular, this should give you what you want

```
n <- sum(mydf$tax == "a")
sum(as.matrix(distances(mydf[mydf$tax == "a", 1:2])), na.rm = TRUE) / (n * (n-1))
```

2. You can cast the `distances` object directly to a `dist` object with

```
mean(as.dist(distances(mydf[mydf$tax == "a", 1:2])), na.rm = TRUE)
```

3. Recreating the `distances` object for every group is suboptimal. Instead, create it once, and use the function `distance_matrix()` to extract the relevant parts. This returns a `dist` object by default.

```
mean(distance_matrix(all.dist2, indices = which(mydf$tax == "a")))
```

Please refer to the documentation for additional details.
